version: '3.8'

services:
  # Serviço do Banco de Dados
  postgres_db:
    image: postgres:15-alpine
    container_name: hotel_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432" # Porta externa : Porta interna
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hotel-network

  # Serviço da Interface Gráfica (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Acessaremos via localhost:5050
    depends_on:
      - postgres_db
    networks:
      - hotel-network

volumes:
  pgdata: # Volume persistente para os dados do banco

networks:
  hotel-network:
    driver: bridge